### PR TITLE
docs(exec): Document use with Eask

### PR DESCRIPTION
**Pull request by jcs090218**
Hi, I want to add document regarding the use with Eask.

Cask is basically unmaintained, so I would like to introduce a new tool [Eask](https://github.com/emacs-eask/cli). It's very similar to Cask, with only a few syntaxes and command differences. LMKWYT?

Thanks!

### CODE REVIEW

**Comment by jcs090218** [comment]
cc @snogge

**Comment by snogge** [comment]
I've seen it, haven't had time to review yet.

**Comment by jcs090218** [comment]
Ah, okay. Sorry for the annoyance.

**Comment by snogge** [comment]
Thank you.

**Comment by jcs090218** [comment]
Thank you so much! :D

**Pull request merged**
