### PR TITLE
feature/windows-bin-support: Added a batch script that execs the butt…

### PR DESCRIPTION
**Pull request by howdoicomputer**
…ercup script using bash

### CODE REVIEW

**Comment by howdoicomputer** [comment]
I'm a Windows user and this allows me to run `cask exec buttercup`.

**Comment by jorgenschaefer** [comment]
Nice, and thank you for the contribution! Could you squash the two commits and add a newline at the end of that file? :-)

**Comment by howdoicomputer** [comment]
@jorgenschaefer There we go! Let me know if anything else is needed. This batch script depends on `bash` being installed but makes no effort to check to see that it is. However, I think it'd be pretty easy for an explorer to figure that out. Will be less of an issue when the Windows Subsystem for Linux rolls out.

**Comment by jorgenschaefer** [comment]
I do not have windows so can not test this, but I think this works better than no batch script, so great. Thanks a lot for the contribution! :-)

**Comment by howdoicomputer** [comment]
@jorgenschaefer That was my line of thought as well. This unblocks me for my projects so I'm more than happy to contribute. Thanks for the merge!

**Pull request merged**
