### PR TITLE
Add projectile integration info to Readme

### PR DESCRIPTION
**Pull request by ebpa**
Example integration for projectile using dir-locals that should save people a bunch of time.

### CODE REVIEW

**Comment by ebpa** [comment]
Simply a suggestion.  Feedback welcome.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the suggestion! I hesitate to add this to the README, as the README should not grow too large. But I have activated the wiki feature on the repo, could you just add it to the wiki? :-) Thank you!

**Comment by ebpa** [comment]
I realized I misspoke in the PR (s/Readme/running-tests.md/).  You probably
noticed.

I will; gladly.  Thanks for enabling that on the repository.  Or perhaps
would another `.md` if running-tests.md would be getting too long?  It's
really nice having the documentation linked to from the landing document.
I'm not sure how robust links into the wiki are given they are technically
in a separate branch.  I can do either.

:+1:

**Comment by jorgenschaefer** [comment]
Oh, actually, I had not noticed! :-D In that case, you are right, keeping it in one spot is a good idea.

Thank you for the contribution!

**Comment by ebpa** [comment]
Thank you!  With buttercup you've made testing in elisp a joy!

**Pull request merged**
