### PR TITLE
Use advice-add instead of obsolete defadvice

### PR DESCRIPTION
**Pull request by tarsius**
... and other minor copy editing.

### CODE REVIEW

**Review by snogge — APPROVED** [review]

**Comment by snogge** [comment]
Maybe it's time to drop the 24.3 support...

**Comment by tarsius** [comment]
I didn't realize there still was/is support for a pre-nadvice Emacs release. Personally I would drop support for 24 at this point, but that is of course your call. I've actually dropped support for 25 for some packages recently and so far nobody complained (which wasn't the case when I last tried that two years ago, or so.)

**Comment by snogge** [comment]
I try to keep support for as long as possible as buttercup is the kind
of tool that is used to verify that packages work on older Emacsen. 
But I've been looking for excuses to drop support for the older
versions, so I'll drop Emacs 24.3 now.

**Comment by snogge** [comment]
Thank you for the contribution.

**Comment by tarsius** [comment]
> But I've been looking for excuses to drop support for the older versions, so I'll drop Emacs 24.3 now.

Some maintainers of packages that use buttercup will feel the same way. :wink:

**Pull request merged**
