### PR TITLE
Configurable stack traces

### PR DESCRIPTION
**Pull request by DarwinAwardWinner**
This implements two variables to control the printing of stack traces. `buttercup-stack-frame-style` can be set to `short`, `long`, or `pretty`. `buttercup-stack-frame-add-prefixes` can be set non-nil to prefix each frame with a lambda for function calls or an M for macros and special forms.

I still need to add a command-line argument for this.

### CODE REVIEW

**Comment by DarwinAwardWinner** [comment]
I added a command-line argument to control trace style.

**Comment by DarwinAwardWinner** [comment]
FYI If you don't like the lambda/M prefixes, you can just skip 82e7e58.

**Comment by jorgenschaefer** [comment]
After thinking about it for a moment, I like the prefixes – but I don't think there should be an extra option for them, they can be the default for "pretty" stack traces and not there for the rest? What do you think?

**Comment by DarwinAwardWinner** [comment]
Sounds good to me. I'll make that change.

**Comment by DarwinAwardWinner** [comment]
Ok, I implemented that change and squashed everything.

**Comment by jorgenschaefer** [comment]
This seems to conflict with one of your other changes I'm afraid, could you look again?

**Comment by DarwinAwardWinner** [comment]
Ok, I rebased it onto master.

**Pull request merged**
