### PR TITLE
Fixed misspelling in the documentation

### PR DESCRIPTION
**Pull request by sergeyklay**
Hello,

There is a fix for few minor typos.

### CODE REVIEW

**Comment by snogge** [comment]
Actually, I think @jorgenschaefer used `iff' in the mathematical sense, meaning `if and only if'.

**Comment by jorgenschaefer** [comment]
I did, but that's super nerdy …

**Comment by sergeyklay** [comment]
Got it. Should I close this then?

**Comment by jorgenschaefer** [comment]
Maybe merge it to avoid further confusion? @snogge what do you think?

**Pull request merged**
